use trainingDB;

CREATE TABLE CUSTOMERS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(16) NOT NULL,
SURNAME VARCHAR(25) NOT NULL,
Age INT NULL
);

CREATE TABLE CONTACTS(
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
ID_CUSTOMER BIGINT NOT NULL,
TYPE TINYINT NOT NULL,
CONTACT VARCHAR(100) NOT NULL
);

ALTER TABLE CONTACTS ADD FOREIGN KEY (ID_CUSTOMER) REFERENCES CUSTOMERS(ID);